lenguage: node_js
node_js:
  - "13"
deploy:
  provider: heroku
  app: shareyourideas-nodejstwo
  api_key:
    secure: kPPa15M5mztLuNik2ZK20Svd8FeRRxKwrpuZ+xaJY21cfm8fnygk9Y6+GMe7wGMTpTGd+Lps2Yuoobryymn/BLNB7BwUKTIMvo7piaptkbg1vrXgUC0yb9Hc5V8E+GwWs/FL/r/aoymj5/y+XHLF/CYTsF4QDaMMcb47K7NpinazgZm5yMINWone/pVnb6BDC9ENWTU3ELJE7Bp2z4VXrCICkndpGfWrjAhqL72VDdl3dSBve4OKQck94BmIFCPMmiLZobPVmHWB6TP6alrWfv2ghc88UTnULmEnI9RdVnNBkp3jJK3wHCP0gY2i0teO19ziCU9x28OBPfpu2zy/COS9FLVzjcKk0ooYiKPXZxKF7PJzLP/1zHj9+BO2BxkgDbswHD+g9it6MssaJTJFI1cKl6JAENa6VUpOQ0RPlZNHUHYlJT9slCdoxnBSsVt+MfLT0FhVytllWnAY+HvZus81s1Q8J0vPZ8i36kb7Mnr3rvsZt45xYXdXAVNpT/DU3ClXgypxy41tNeJH476QO6SgRP2N1X7IfMmEREPL005YBxE2UvEW9Cm/66pJOih0U6sEqjEB+YX3wJvpZLTMpGOSylbUb0RJpoTPE0trHmFBObhPx1GsVa9CsmNnEMLLamGolHtnB8zLfbJajGMWz2OaBsWSfNwCaPgJ0SkLv+Y=
