lenguage: node_js
node_js:
  - 13

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: shareyourideas-nodejstwo
  api_key:
    secure: f6eGWHH9355xjOzMPW+0F060zj4Hpr7btM2Tg8rnjGMbVumz7IeSwhKqbNldBJ+hbRH+Epe4iGNSiyOYQ+xPabLx9ZYg4xJA6vCYx2nxX0NU+3gN34CnIrTJnaVhg5xB7elq85QfICsb+OLIYiaHaS7np83/G0OLk1cFGwaSKrFzMYNVQCiaRk9AhPE8dAKHOMt3iW0HQg8LIrRvIm5qFsMifTR3rJgRZwbMkzALTD2W/ebZadz4TqEiNmA+BSGbx59gU1GzA2lde9ZQFBm5Ubc1c4zOqRrvZmuKDxXIwWterEAQ2azUDJ7liaJ1eppSmKWP9lZaq3sYm4GD6Dtv2xmZl3WG7hSV11Enkyj8qROV7/1RZo4SdSbMT0+DWU1A6wQnW9rsVZWD1K+QplzC6d3cKf5bL3QxfltKBQPy1XzT0FQGjuuvEdqqHf9fNxmTtcv0ts2q5JpKeHSmqztOlJL7LAUfcxbGU0IYFSvO+bgMBphme3C5R+VZAOwQ5rD7+bvszMxm3U5H/Nz8GoXy/8jB5FFzuT7HLXXGf6YLoxckl0Jq9ejASuRvCSXFfzC+0kREN5ay4o59nG2bYvKHtKrP8r2j7elgLfhid/k0b7K1mYd6RAdU/VGkWgSQqaLzEmrC7FXyWF/iJABScjc34l9GRSxMA69X03FUNDCE4io=
